parameters:
    amp1:
        val: 1.0
        active: True
        lb: 0.01
        ub: 3.75
    amp2:
        val: 1.0
        active: True
        lb: 0.01
        ub: 3.75
    amp3:
        val: 1.
        active: True
        lb: 0.01
        ub: 3.75
    lam:
        val: 526.5
        active: True
        lb: 523.0
        ub: 528.0
    Te:
        val: 0.087
        active: True
        lb: 0.01
        ub: 1.5
    Te_gradient:
        val: 0.0
        active: False
        lb: 0.
        ub: 10.
        num_grad_points: 1
    Ti:
        val: 0.043
        active: False
        lb: 0.001
        ub: 3.0
    Z:
        val: 6.
        active: True
        lb: 1.0
        ub: 25.0
    A:
        val: 14.
        active: False

    ud:
        val: 0.0
        active: True
        lb: -2.0
        ub: 2.0
    Va:
        val: 1.1
        active: True
        lb: -2.5
        ub: 2.5
    ne:
        val: 0.06
        active: True
        lb: 0.001
        ub: 1.0
    ne_gradient:
        val: 0.
        active: False
        lb: 0.
        ub: 15.
        num_grad_points: 1
    m:
        val: 3.2
        active: True
        lb: 2.0
        ub: 5.0
    fe:
        val: []
        active: False
        length: 3999
        type:
            DLM:
        lb: -100.
        ub: -0.5
        fe_decrease_strict: False
        symmetric: False

data:
    shotnum: 101675
    lineouts:
        type:
            pixel
        start: 320
        end: 680
        skip: 24
    background:
        type:
            pixel
        slice: 900

other:
    extraoptions:
        load_ion_spec: True
        load_ele_spec: True
        fit_IAW: True
        fit_EPWb: True
        fit_EPWr: True
    refit: False
    refit_thresh: 5.0
    gain: 135

mlflow:
    experiment: inverse-thomson-scattering
    run: single_pass_zach_test4